# Generated by Django 3.1 on 2020-10-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fisico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fisico.fisico')),
            ],
        ),
    ]
