# Generated by Django 3.1 on 2020-10-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
        ('fisico', '0001_initial'),
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='oficina',
            field=models.ManyToManyField(to='oficina.Oficina'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='dono',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fisico.fisico'),
        ),
    ]
