# Generated by Django 3.1 on 2020-09-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('cnpj', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nomeFantasia', models.CharField(max_length=40)),
                ('razaoSocial', models.CharField(max_length=40)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('telefone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
