# Generated by Django 3.1 on 2020-10-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.ManyToManyField(to='oficina.Oficina'),
        ),
    ]
