# Generated by Django 3.1 on 2020-10-08 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veiculo', '0002_auto_20201007_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status', models.BooleanField()),
                ('desconto', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('funcionario', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('placaVeiculo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='veiculo.veiculo')),
            ],
        ),
    ]
