# Generated by Django 3.1 on 2020-10-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
