# Generated by Django 3.1 on 2020-10-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_auto_20200930_1527'),
        ('ordemservico', '0002_auto_20201008_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='servico',
            field=models.ManyToManyField(to='servico.Servico'),
        ),
    ]
