# Generated by Django 3.1 on 2020-10-01 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='cliente.cliente')),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('nomeFantasia', models.CharField(max_length=50)),
                ('razaoSocial', models.CharField(max_length=50)),
            ],
            bases=('cliente.cliente',),
        ),
    ]
